### ISSUE TITLE
Won't run on PHP 5.5, Linux Mint 16

### ISSUE THREAD

**Issue by girvo** [d11wtq/boris#65]
Hi all,

Tried the Phar and the git repo, can't get Boris to launch at all on Linux Mint 16, with PHP 5.5.3

````
PHP Warning:  pcntl_signal() has been disabled for security reasons in /home/josh/Apps/boris/lib/Boris/Boris.php on line 141
PHP Warning:  pcntl_fork() has been disabled for security reasons in /home/josh/Apps/boris/lib/Boris/Boris.php on line 148
PHP Notice:  fwrite(): send of 1 bytes failed with errno=32 Broken pipe in /home/josh/Apps/boris/lib/Boris/EvalWorker.php on line 205
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Socket error: failed to write data' in /home/josh/Apps/boris/lib/Boris/EvalWorker.php:206
Stack trace:
#0 /home/josh/Apps/boris/lib/Boris/EvalWorker.php(88): Boris\EvalWorker->_write(Resource id #11, '?')
#1 /home/josh/Apps/boris/lib/Boris/Boris.php(171): Boris\EvalWorker->start()
#2 /home/josh/Apps/boris/bin/boris(16): Boris\Boris->start()
#3 {main}
  thrown in /home/josh/Apps/boris/lib/Boris/EvalWorker.php on line 206
````

That's my stacktrace when running ````bin/boris````

**Comment by tejasmanohar** [comment]
Works for me in Arch, Ubuntu, and OS X. Have you guys tried to isolate this in a virtual box like Vagrant? I'll close this to inactivity, but comment again and it's back.
